name: QA

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build all packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v6

      - name: install packages
        uses: ./.github/common-actions/install

      - name: build packages
        run: pnpm build

  lint:
    name: check lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: install packages
        uses: ./.github/common-actions/install

      - name: run biome lint check
        run: pnpm biome ci

  types:
    name: typecheck all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: install packages
        uses: ./.github/common-actions/install

      - name: run typecheck
        run: pnpm tsc --noEmit
